# Site settings
title:          Tale
description:    "100 days of ML Code"
baseurl:        ""
url:            "https://devyohan.github.io/100_Days_of_ML_Code/"

# Author
author:
  name:         Yohan Park (DevYohan)
  url:          https://www.devyohan.io
  email:        devyohans@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
